config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations]
  root 'home#index'
  get '/bebes', to: 'bebes#index'
  post 'bebes', to: 'bebes#create'

  post '/votacion', to: 'votaciones#votar', as: 'votar'
  get '/votacion', to: 'votaciones#mostrar_duelo', as: 'votacions'
  delete '/votacion', to: 'votaciones#reiniciar_votos', as: 'reiniciar_votos'

  post '/generar_cuadros', to: 'competition#generar_cuadros', as: 'crear_cuadro'
  get '/cuadro_masculino', to: 'competition#competicion_masculina', as: 'cuadro_masculino'
  get '/cuadro_femenino', to: 'competition#competicion_femenina', as: 'cuadro_femenino'
  get '/ganador_masculino', to: 'competition#ganador_masculino', as: 'ganador_masculino'
  get '/ganador_femenino', to: 'competition#ganador_femenino', as: 'ganador_femenino'
  post '/competition_vote', to: 'competition_votes#create', as: 'competition_vote'
  delete '/competition_vote', to: 'competition_votes#delete', as: 'competition_vote_delete'
end

app/models/bebe.rb
class Bebe < ApplicationRecord
    has_many :votacions
    has_many :competitions
    has_many :competition_votes
    belongs_to :created_by, class_name: "User", foreign_key: "created_by"

    validates :nombre, presence: true, uniqueness: true
    validates :sexo, presence: true

    enum prioridad: {
        'Alta' => 0,
        'Media' => 1,
        'Baja' => 2
      }

    enum sexo: {
        'Hombre' => 0,
        'Mujer' => 1
    }
end

app/controllers/bebes_controller.rb
class BebesController < ApplicationController
    before_action :authenticate_user!

    def index
        @bebes = Bebe.order(puntuacion: :desc)
        @new_bebe = Bebe.new
    end

    def create
        if Bebe.where(created_by: current_user, sexo: bebe_params[:sexo]).count < 8
            if Bebe.where(prioridad: "Alta", created_by: current_user).count == 2 && params[:prioridad] == "Alta"
                redirect_back fallback_location: root_path, alert: 'No puedes dar más prioridades "Alta"'
            else
                @bebe = Bebe.new(bebe_params)
                @bebe.created_by = current_user

                if @bebe.save
                    # Manejar el éxito de la creación del bebé
                    flash[:notice] = 'Bebé creado exitosamente.'
                    redirect_to :bebes
                else
                    # Manejar errores de validación o creación
                    redirect_back fallback_location: root_path, alert: 'No se pudo crear el nombre del bebé.'
                end
            end
        else
            redirect_back fallback_location: root_path, alert: 'Has creado el máximo de bebés.'
        end
    end
    
      
    private

    def bebe_params
        params.require(:bebe).permit(:nombre, :prioridad, :sexo)
    end
end

app/helpers/bebes_helper.rb
module BebesHelper
end

app/views/bebes/_form.html.erb
<%= form_for @new_bebe do |f| %>
    <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :sexo %>
        <%= f.select :sexo, options_for_select(['Hombre', 'Mujer']), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :prioridad %>
        <%= f.select :prioridad, options_for_select(['Alta', 'Media', 'Baja']), {}, class: 'form-control mb-2' %>
    </div>

    <div class="form-group">
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/bebes/index.html.erb
<!-- Button trigger modal -->
<% if current_user.has_role?([:admin, :padres])%>
    <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Añadir nombre
    </button>
<% end %>

<div class="d-md-flex flex-md-row">
    <div class="col-md-6 mb-3 me-4">
        <% if bracket_generated? %>
            <%= link_to 'Cuadro masculino', cuadro_masculino_path ,class:"btn btn-outline-secondary text-decoration-none mt-3 mb-3"%>
        <% end %>

        <% if winner?('Hombre') %>
            <%= link_to 'Ganador', ganador_masculino_path ,class:"btn btn-outline-success text-decoration-none mt-3 ms-3 mb-3"%>
        <% end %>

        <h2 class="text-center nombres-titulo font-edu">Nombres Masculinos</h2>
        <table class="table table-light table-hover m-auto text-center font-play">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Papá/Mamá:</th>
                    <th>Puntuación</th>
                </tr>
            </thead>
            <tbody>
                <% @bebes.each do |bebe| %>
                    <% if bebe.sexo == 'Hombre' %>
                        <tr>
                            <td><%= bebe.nombre %></td>
                            <td><%= bebe.created_by.nombre %></td>
                            <td><%= bebe&.puntuacion %></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-md-6">
        <% if bracket_generated? %>
            <%= link_to 'Cuadro femenino', cuadro_femenino_path ,class:"btn btn-outline-secondary text-decoration-none mt-3 mb-3"%>
        <% end %>

        <% if winner?('Mujer') %>
            <%= link_to 'Ganadora', ganador_femenino_path ,class:"btn btn-outline-success text-decoration-none mt-3 ms-3 mb-3"%>
        <% end %>

        <h2 class="text-center nombres-titulo font-edu">Nombres Femeninos</h2>
        <table class="table table-light table-hover m-auto text-center font-play">
            <thead>
                <tr>
                <th>Nombre</th>
                <th>Mamá/Papá:</th>
                <th>Puntuación</th>
                </tr>
            </thead>
            <tbody>
                <% @bebes.each do |bebe| %>
                    <% if bebe.sexo == 'Mujer' %>
                        <tr>
                        <td><%= bebe.nombre %></td>
                        <td><%= bebe.created_by.nombre %></td>
                        <td><%= bebe&.puntuacion %></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<div class="w-100 my-3 d-flex flex-column">
    <div class="d-flex justify-content-around">
        <% if Competition.first.present? %>
            <%= link_to 'Cuadro masculino', cuadro_masculino_path ,class:"btn btn-outline-secondary text-decoration-none"%>
            <%= link_to 'Cuadro femenino', cuadro_femenino_path ,class:"btn btn-outline-secondary text-decoration-none"%>
        <% end %>
    </div>
    <div>
        

        <% if all_users_voted? && !bracket_generated? %>
            <%= button_to 'Generar Cuadros', crear_cuadro_path, method: :post, class: 'btn btn-outline-success' %> 
        <% end %>
    </div>
</div>

<% if current_user.votacions.any? && !bracket_generated? %>
    <button type="button" class="btn btn-outline-danger my-4" data-bs-toggle="modal" data-bs-target="#exampleModal2">
        Reinicia tus votos
    </button>
<% end %>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Añadir nombre del bebé</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', bebe: @bebe_new %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Estás seguro de que quieres reiniciar tus votos?</h5>
      </div>
      <div class="modal-footer">
        <%= button_to 'Reiniciar', reiniciar_votos_path, method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>