config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations]
  root 'home#index'
  get '/bebes', to: 'bebes#index'
  post 'bebes', to: 'bebes#create'

  post '/votacion', to: 'votaciones#votar', as: 'votar'
  get '/votacion', to: 'votaciones#mostrar_duelo', as: 'votacions'
  delete '/votacion', to: 'votaciones#reiniciar_votos', as: 'reiniciar_votos'

  post '/generar_cuadros', to: 'competition#generar_cuadros', as: 'crear_cuadro'
  get '/cuadro_masculino', to: 'competition#competicion_masculina', as: 'cuadro_masculino'
  get '/cuadro_femenino', to: 'competition#competicion_femenina', as: 'cuadro_femenino'
  get '/ganador_masculino', to: 'competition#ganador_masculino', as: 'ganador_masculino'
  get '/ganador_femenino', to: 'competition#ganador_femenino', as: 'ganador_femenino'
  post '/competition_vote', to: 'competition_votes#create', as: 'competition_vote'
  delete '/competition_vote', to: 'competition_votes#delete', as: 'competition_vote_delete'
end

app/views/shared/_flash_alerts.html.erb
<% flash.each do |key, message| %>
    <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light font-edu fs-5">
  <div class="container-fluid">
    <a class="navbar-brand logo" href="/">NombreBB</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to 'Home', root_path, class:"nav-link #{'active' if current_page?(root_path)}" %>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Lista', bebes_path, class:"nav-link #{'active' if current_page?(bebes_path)}" %>
                </li>
                <% if !bracket_generated? && all_babies_created? %>
                    <li class="nav-item">
                        <%= link_to 'Vota!', votacions_path, class:"nav-link #{'active' if current_page?(votacions_path)}" %>
                    </li>
                <% end %>
            <% end %>
        </ul>
        <ul class="d-flex navbar-nav">
            <% if user_signed_in? && current_user&.has_role?(:admin) %>
                <!-- Enlace de "Sign Up" -->
                <li class="nav-item">
                    <p class="nav-link mb-0 text-info">Hola <%= current_user.nombre %>!</p>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                </li>

                <!-- Enlace de "Sign Out" -->
                <li class="nav-item">
                    <%= link_to 'Salir', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
                </li>
            <% elsif user_signed_in? %>
                <!-- Enlace de "Sign In" -->
                <li class="nav-item">
                    <p class="nav-link mb-0 text-info">Hola <%= current_user.nombre %>!</p>
                </li>

                <li class="nav-item">
                    <%= link_to 'Salir', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
                </li>
            <% else %>
                <li class="nav-item">
                    <a class="nav-link" href="/users/sign_in">Login</a>
                </li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/shared/_votacion_form.html.erb
<%= form_for @votacion do |f| %>
    <%= f.hidden_field :user_id, value: @usuario_actual.id %>
    <%= f.hidden_field :bebe_1_id, value: @bebe_1.id %>
    <%= f.hidden_field :bebe_2_id, value: @bebe_2.id %>

    <h2 class="text-center">Duelo de Nombres de Bebés</h2>

    <div class="w-100 shadow rounded p-3 col-6 p-5">
        <div class="text-center mb-3">
        <% [@bebe_1, @bebe_2].each do |bebe| %>
            <label class="nombre-capsula" for="bebe_<%= bebe.id %>">
            <span class="nombre <%= f.object.bebe_id == bebe.id ? 'seleccionado' : '' %>">
                <%= bebe.nombre %>
                <%= f.radio_button :bebe_id, bebe.id, id: "bebe_#{bebe.id}", class: "nombre-radio" %>
            </span>
            </label>
        <% end %>
        </div>
        
        <%= f.submit "Votar", class: "btn btn-primary d-block mx-auto px-5" %>
    </div>
<% end %>